Wallet is safe to use concurrently
alisavch/wallet pull request #5
Opened 2021-05-28 12:34 UTC by alisavch

2021-05-31 07:29 UTC, roflanKisel requested changes
Good job!

Checkout comments

2021-05-31 07:29 UTC, roflanKisel commented on wallet.go
>  )
- Import ordering must be correct

2021-05-31 07:29 UTC, roflanKisel commented on wallet_test.go
>  )
- Import ordering

2021-05-31 07:29 UTC, roflanKisel commented on wallet_test.go
> +	wg.Wait()
- It's better to keep non-concurrent tests as they were previously and add another subtest for concurrent test
- To test concurrency you should show that method works fine when multiple goroutines call it, for instance 5 goroutines

2021-05-31 07:29 UTC, roflanKisel commented on wallet_test.go
> +	wg.Wait()
Same as for Deposit

2021-05-31 07:29 UTC, roflanKisel commented on wallet_test.go
> +	wg.Wait()
Same as for Deposit

2021-05-31 07:29 UTC, roflanKisel commented on wallet.go
> +	mu      sync.Mutex
- Here we can use struct embedding instead of making new field for mutex

2021-05-31 07:37 UTC, alisavch commented on wallet.go
>  )
oh thanks, I forgot about goimports

2021-05-31 07:39 UTC, alisavch commented on wallet_test.go
> +	wg.Wait()
ok, thanks, I will consider this

2021-05-31 08:45 UTC, roflanKisel requested changes

2021-05-31 08:45 UTC, roflanKisel commented on wallet.go
> +	defer w.Unlock()
- We should lock mutex when multiple goroutines could access the same memory space, so it is unnecessary to lock before value validation

2021-05-31 08:45 UTC, roflanKisel commented on wallet.go
> +	defer w.Unlock()
Same as for Deposit

2021-05-31 08:45 UTC, roflanKisel commented on wallet_test.go
> +			wg.Wait()
Basically this is not showing the safety of code because each goroutine has it's own wallet
You need to refactor test method so all goroutines will have the same wallet instance
Probably you'll need to add special test cases for concurrency testing

2021-05-31 08:45 UTC, roflanKisel commented on wallet_test.go
> +		})
Same as for TestWallet_Deposit

2021-05-31 08:45 UTC, roflanKisel commented on wallet_test.go
> +		t.Run(tc.name+" safe for concurrent use", func(t *testing.T) {
Same as for TestWallet_Deposit

2021-05-31 15:05 UTC, alisavch commented on wallet_test.go
> +		})
Balance returns the same result in both cases. I'm not sure if another test case is needed for this

2021-06-01 11:45 UTC, roflanKisel requested changes

2021-06-01 11:45 UTC, roflanKisel commented on wallet_test.go
> +			wg.Wait()
We need to do wg.Wait before getting wallet's balance, therefore we don't need time.Sleep at all
This case with sleep looks weird in test

2021-06-01 11:45 UTC, roflanKisel commented on wallet_test.go
> +			wg.Wait()
Same as Deposit

2021-06-01 11:45 UTC, roflanKisel commented on wallet.go
> +	w.Unlock()
It looks weird, doesn't it?

2021-06-01 12:12 UTC, alisavch commented on wallet_test.go
> +			wg.Wait()
ok, I realized, thanks

2021-06-01 14:00 UTC, roflanKisel submitted a review, later dismissed
Good job! LGTM, but it would be nice if you added generic test helper for concurrency testing.

2021-06-02 10:20 UTC, roflanKisel approved these changes
LGTM

2021-06-02 11:21 UTC, merged